project:
  type: website
  output-dir: docs

website:
  title: "APAN Maths Camp"
  google-analytics: ""
  repo-url: https://hgoers.github.io/APAN_maths_camp/
  repo-actions: [issue]

  favicon: "/files/img/hex-testudo.png"

  navbar:
    pinned: true
    background: "#C31832"
    right:
      - href: index.qmd
        text: Home
      - href: content/00-02-introduction.qmd
        text: Content

  sidebar:
    - title: "Content"
      style: "docked"
      contents:
        - section: "Introduction to Political Science Data Analysis"
          contents: 
            - content/00-02-introduction.qmd
            - content/01-02-measurement.qmd
#            - content/02-experiments.qmd
#            - content/02-02-surveys_to_pops.qmd
#            - content/03-02-bivariate.qmd
#            - content/04-02-linear_regression.qmd
#            - content/05-02-probability.qmd
#            - content/06-02-uncertainty.qmd
        - section: "Introduction to R"
          contents:
            - content/00-01-introduction.qmd
#            - content/01-01-visualization.qmd         
#            - content/02-01-transformation.qmd
#            - content/03-01-wrangling.qmd
#            - content/04-01-merging.qmd
#            - content/05-01-programming.qmd
#            - content/06-01-communicating.qmd
            
            
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-Non Commercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [Heavily inspired by course websites built by Dr Andrew Heiss](https://www.andrewheiss.com/teaching/)

format:
  html:
    theme: litera
    css: html/custom.css
    toc: true
    highlight-style: monokai

editor: visual

